-- hex_ro access inside ONE tenant database. SUPERSEDED: the canonical, maintained copy is
-- Backend-Server scripts/tenant_onboarding/onboard_tenant.sql (which also grants
-- crm_sync_ro). This file is kept only as a pointer so the runbook history makes sense.
--
-- Access model (allowlist, not denylist): hex_ro may SELECT a fixed set of metadata tables
-- (companies, users, brands, brand_team_members, projects, admin_requests, marketing_files,
-- prior_approved_files) plus two content-free views, analytics.assets (n_cg_operations
-- without prompt/messages/html/chat/source/metadata blobs) and analytics.mlr_reviews
-- (qc results as counts and flags). Everything else is revoked first, default privileges
-- are removed, and verification fails if any grant exists outside the list. Generated
-- content, chat transcripts (n_cg_operation_messages, chat_messages), HTML versions,
-- prompts, templates and configuration are unreachable by construction.
--
-- Run the Backend-Server script; do not maintain a second copy here.
